# Дополнительный docker-compose файл с prod конфигурацией.
# Самостоятельно не используется.
# Запускать только вместе с базовым docker-compose.yml.
#
# Пример:
# docker compose -p studyoverflow-prod -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.prod up

services:
  postgres:
    env_file:
      - .env.prod

  # Контейнер для подготовки среды бекенда (миграции и сборка статики)
  studyoverflow-init:
    build:
      context: ./studyoverflow
      dockerfile: Dockerfile
      target: prod-image
    image: ${STUDYOVERFLOW_IMAGE}:${IMAGE_TAG:-prod}
    # Контейнер останавливается после выполнения команд и не перезапускается
    restart: "no"
    env_file:
      - .env.prod
    networks:
      - studyoverflow_network
    volumes:
      - staticfiles:/app/studyoverflow/staticfiles
    # Контейнер запускается от root, нужно для выполнения chown (смены прав каталога)
    user: root
    # 1) Передаются права на каталог пользователю userdj.
    # 2) Выполняются миграции БД.
    # 3) Собираются статические файлы.
    command: >
      sh -c "chown -R userdj:groupdjango /app/studyoverflow/staticfiles &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --clear"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  studyoverflow-1:
    image: ${STUDYOVERFLOW_IMAGE}:${IMAGE_TAG:-prod}
    # --proxy-headers - Daphne доверяет заголовкам запроса, который присылает Nginx
    # -b (--bind) 0.0.0.0 - IP-адрес, который слушает сервер, 0.0.0.0 указывает принимать соединения
    #   на всех сетевых интерфейсах (открывает порт на всех IP-адресах)
    # -p (--port) 8000 - номер порта, который слушает Daphne
    # studyoverflow.asgi:application - точка входа ASGI-приложения
    command: daphne --proxy-headers -b 0.0.0.0 -p 8000 studyoverflow.asgi:application
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    volumes:
      - staticfiles:/app/studyoverflow/staticfiles
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      studyoverflow-init:
        condition: service_completed_successfully

  studyoverflow-2:
    image: ${STUDYOVERFLOW_IMAGE}:${IMAGE_TAG:-prod}
    restart: unless-stopped
    command: daphne --proxy-headers -b 0.0.0.0 -p 8000 studyoverflow.asgi:application
    volumes:
      - staticfiles:/app/studyoverflow/staticfiles
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    networks:
      - studyoverflow_network
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      studyoverflow-init:
        condition: service_completed_successfully

  celery-worker:
    image: ${STUDYOVERFLOW_IMAGE}:${IMAGE_TAG:-prod}
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      studyoverflow-init:
        condition: service_completed_successfully

  celery-beat:
    image: ${STUDYOVERFLOW_IMAGE}:${IMAGE_TAG:-prod}
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      studyoverflow-init:
        condition: service_completed_successfully

  grafana:
    env_file:
      - .env.prod
    environment:
      # Домен, на котором доступна Grafana
      - GF_SERVER_DOMAIN=${SITE_DOMAIN}
      # Базовый URL, по которому пользователи заходят в Grafana (нужен, чтобы Grafana правильно строила пути к своим файлам)
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      # Разрешает Grafana отдавать контент по вложенному пути (например /grafana/), а не из корня домена (/)
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

  nginx:
    build: ./nginx
    image: ${NGINX_IMAGE}:${IMAGE_TAG:-prod}
    restart: unless-stopped
    networks:
      - studyoverflow_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # :ro - read-only
      - staticfiles:/app/studyoverflow/staticfiles:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    environment:
      - NGINX_SSL_ENABLED=${NGINX_SSL_ENABLED:-false}
    depends_on:
      - studyoverflow-1
      - studyoverflow-2

  certbot:
    image: certbot/certbot
    volumes:
      # Certbot сохранит выпущенные SSL-сертификаты, чтобы Nginx смог прочитать их
      - certbot-etc:/etc/letsencrypt
      # Certbot создаст временный файл, чтобы доказать Let's Encrypt, что домен действительно указывает на
      # запущенный сервер (IP-адрес).
      # Let's Encrypt отправит запрос по адресу http://домен/.well-known/acme-challenge/секретный_файл,
      # файл создает перед этим сам Certbot, заранее попросив у Let's Encrypt токен и сделав файл с ним.
      - certbot-webroot:/var/www/certbot
    # Контейнер должен быть запущенным, чтобы выполнялись команды.
    # Контейнер запускает командную оболочку /bin/sh (-c - command), в которой выполняются команды:
    # - trap exit TERM - заставляет контейнер останавливаться сразу при команде остановки, иначе сигнал
    #   об остановке будет проигнорирован, а процесс принудительно завершен Docker через 10 секунд;
    # - while :; do ... done; - создает бесконечный цикл, ":" - True, do ... done - тело цикла;
    # - sleep 12h & wait $${!} - запускает таймер сна в фоновом режиме на 12 часов;
    # - wait $${!} - заставляет скрипт остановиться и ждать окончания работы этого таймера сна,
    #   символ "!" - ID последнего запущенного фонового процесса, то есть sleep.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; done;'"

  flower:
    env_file:
      - .env.prod
    environment:
      # FLOWER_BASIC_AUTH задается в .env.prod
      # FLOWER_URL_PREFIX - указывает Flower, что он доступен не из корня сайта, а по url
      - FLOWER_URL_PREFIX=/flower

volumes:
  certbot-etc:
  certbot-webroot:
