# Облегчённая production-lite-конфигурация для VPS с ограниченной RAM (1 Гб).
#
# Самостоятельно не используется.
# Запускать только вместе с docker-compose.yml и docker-compose.prod.yml.
#
# Пример:
#   docker compose -p studyoverflow-prod -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.prod-lite.yml --env-file .env.prod up

services:
  # В lite-режиме при обычном запуске без указания --profile backend-2
  # studyoverflow-2 не запустится.
  studyoverflow-2:
    profiles:
      - backend-2

  celery-worker:
    # --pool=prefork - запускает главный celery процесс и дочерние процессы
    # --pool=threads - запускает главный celery процесс и потоки в нем для выполнения задач,
    #   при этом Django пул соединений к БД нужно отключать
    # --pool=gevent - запускает главный celery процесс и один поток, в котором используются зеленые потоки,
    #   кооперативная многозадачность, при этом Django пул соединений к БД нужно отключать
    #
    # 1) Threads и gevent подходят (помимо процессов), потому что большинство задач являются IO-bound задачами.
    # 2) Стандартный пул соединений Django не рассчитан на работу внутри одного процесса
    # с внутренней конкурентностью - ни с гринлетами, ни с настоящими потоками ОС, возникают ошибки
    # при e2e тестировании в celery задачах, поэтому при --pool=threads и при --pool=gevent
    # стандартный пул Django с БД нужно отключать.
    # 3) Можно использовать --pool=threads, а не гринлеты, поскольку gevent
    # имеет конфликт с asyncio event loop внутри Django Channels (celery задачи
    # иногда падали с ошибками, например при e2e тестах), но тогда не получится ограничить потребление ОП
    # worker процесса.
    # 4) Выбирается --pool=prefork с --concurrency=1 и указанием --max-memory-per-child вместо --pool=threads,
    # поскольку процесс celery worker может увеличивать потребление ОЗУ при выполнении задач, но
    # аллоцированная ОП не всегда возвращается ОС. Нужно ограничивать лимит по ОП worker процесса, но при этом,
    # чтобы задачи выполнялись и временно потребление ОП могло превысить лимит, поэтому жесткое ограничение
    # процесса по ОП не подходит, так как тогда задача не выполнится. Подходит флаг --max-memory-per-child
    # от Celery, который перезапускает дочерний worker процесс при превышении им лимита ОП, но строго
    # между выполнением задач, работает только при режиме --pool=prefork, поэтому выбирается данный режим.
    # Задается --max-memory-per-child=130000, указывается число в Кб.
    command: celery -A studyoverflow worker -l info --pool=prefork --concurrency=1 --max-memory-per-child=130000
    environment:
      # Стандартный пул Django соединений с БД (psycopg-pool) несовместим ни с гринлетами,
      # ни с настоящими потоками ОС, поэтому пул отключается, вместо него задается CONN_MAX_AGE.
      DB_USE_POOL: "false"

  # В lite-режиме при обычном запуске без указания --profile monitoring
  # promtail, loki, grafana и flower не запустятся.
  loki:
    profiles:
      - monitoring

  promtail:
    profiles:
      - monitoring

  grafana:
    profiles:
      - monitoring

  flower:
    profiles:
      - monitoring

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-lite
    image: ${NGINX_IMAGE}-lite:${IMAGE_TAG:-prod}
    # В lite-режиме Nginx зависит только от одного backend.
    depends_on: !override
      - studyoverflow-1
