# Базовый docker-compose файл.
# Самостоятельно не используется.
# Запускать только вместе с одним из других файлов конфигурации (dev или prod):
#   docker-compose.dev.yml
#   docker-compose.prod.yml
#
# Примеры:
# docker compose -p studyoverflow-dev -f docker-compose.yml -f docker-compose.dev.yml --env-file .env.dev up
# docker compose -p studyoverflow-prod -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.prod up

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - studyoverflow_network
    healthcheck:
      # ${POSTGRES_USER} - значение подставляется Docker Compose в момент чтения файла docker-compose.yml,
      # до запуска контейнера, $POSTGRES_USER - то же самое, краткая форма, если после переменной пробел или спецсимвол.
      #
      # $$POSTGRES_USER - с двумя $$ Docker заменяет $$POSTGRES_USER на $POSTGRES_USER и не подставляет значение сам,
      # контейнер запускается и Linux Shell внутри контейнера видит знак $ и сам подставляет значение
      # переменной из оперативной памяти.
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - studyoverflow_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  studyoverflow-1:
    restart: unless-stopped
    networks:
      - studyoverflow_network
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-worker:
    restart: unless-stopped
    command: celery -A studyoverflow worker -l info
    networks:
      - studyoverflow_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    restart: unless-stopped
    command: celery -A studyoverflow beat -l info --schedule=/app/studyoverflow/celerybeat_data/celerybeat-schedule
    volumes:
      - celery_beat_data:/app/studyoverflow/celerybeat_data
    networks:
      - studyoverflow_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  loki:
    build: ./monitoring/loki
    image: ${LOKI_IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - loki-data:/loki
    command:
      -config.file=/etc/loki/config.yml
    networks:
      - studyoverflow_network

  promtail:
    build: ./monitoring/promtail
    image: ${PROMTAIL_IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - promtail-data:/run/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - studyoverflow_network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - studyoverflow_network
    depends_on:
      - loki

networks:
  studyoverflow_network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  staticfiles:
  celery_beat_data:
  promtail-data:
  loki-data:
  grafana-data:
