# Конфигурация Promtail. Promtail - это агент, который предназначен для сбора и отправки логов в
# NoSQL БД хранилище логов Loki.
#
# У каждого процесса (docker-контейнера) есть три файловых дескриптора: 0 - stdin (ввод),
# 1 - stdout (стандартный вывод) и 2 - stderr (вывод ошибок).
#
# Docker Daemon следит за потоками вывода 1 и 2 каждого процесса (контейнера) и перехватывает все,
# что туда пишется, сохраняя данные в отдельный файл на диске хоста (отдельный файл под каждый контейнер).
# Docker Daemon для потоков вывода контейнеров настраивает каналы pipe, в которые они пишут, а он слушает,
# внутри контейнеров данные потоков вывода не сохраняются, Daemon сохраняет данные в файлах на хосте.
#
# Считывая данные из двух каналов pipe (от stdout и stderr) контейнера, Daemon копирует их в свой участок
# оперативной памяти, откуда он пишет данные сразу в 2 места:
#   - в один JSON (сохраняется информация, какие данные из stdout, а какие из stderr);
#   - в терминал при docker compose up.
#
# Docker Daemon создает на хосте виртуальный файл /var/run/docker.sock - сокет. Используется для связи
# Docker-клиента (команды docker ps, docker run и так далее) с Docker Daemon. Также используется для связи
# контейнеров с Docker Daemon (API). Это API для управления Docker через Docker Daemon (слушает команды из
# этого сокета), сокет использует как сам Docker, так и контейнеры для информации о других контейнерах.
# Контейнер (процесс) при этом сам общается с ядром хоста, если нужны системные вызовы для работы процесса.
#
# Для просмотра файлов с данными потоков вывода контейнеров и соотнесения их с самими контейнерами
# Promtail использует Docker API, доступ к которому осуществляется через файл сокета — /var/run/docker.sock.
# Для этого в настройках томов Promtail указывается:
#   - /var/run/docker.sock:/var/run/docker.sock (сокет)
#   - /var/lib/docker/containers:/var/lib/docker/containers:ro (папка с файлами логов)
# Слева /var/run/docker.sock - путь к файлу Unix-сокета на хосте, справа /var/run/docker.sock - точка монтирования
# внутри файловой системы контейнера Promtail. Аналогично для папки с файлами логов.
#
# После сопоставления ID контейнеров с их именами через сокет docker.sock агент начинает их непрерывный
# мониторинг. Promtail считывает появляющиеся логи в файлах и считывает их в свою память, затем каждый лог
# проходит обработку: декодирование, добавление метаданных (меток labels, например имя контейнера) и
# дальнейший парсинг самого сообщения.
#
# Promtail собирает обработанные логи в буффере и отправляет в Loki батчами (есть лимиты по времени и
# по памяти для сигнала для отправки в Loki).
#
# После получения 200 ответа от Loki Promtail сохраняет информацию, до какого байта прочитан файл логов контейнера.


# Настройка внутреннего веб-сервера Promtail
server:
  # Порт внутреннего HTTP-сервера Promtail для Health Checks и API для метрик работы самого Promtail,
  # на данный момент для связки Promtail - Loki - Grafana не нужен, 9080 - стандартный порт
  http_listen_port: 9080

  # Значение 0 отключает gRPC-сервер Promtail
  grpc_listen_port: 0

# Секция с настройкой файла с записями позиция чтения логов
positions:
  # Файл, в котором Promtail сохраняет текущую позицию чтения для каждого отслеживаемого файла
  # или для каждого Docker-контейнера
  filename: /run/promtail/positions.yaml

# Список серверов-получателей логов
clients:
  # URL Loki, куда Promtail отправляет логи
  - url: http://loki:3100/loki/api/v1/push

# Список задач по сбору логов, описываются правило, откуда забираются логи
scrape_configs:
  # Имя джобы сбора логов
  - job_name: docker
    # Включает автообнаружение контейнеров
    docker_sd_configs:
      # Путь к сокету Docker Daemon (API)
      - host: unix:///var/run/docker.sock
        # Периодичность опроса Docker API (обновление списка контейнеров каждые 5 секунд)
        refresh_interval: 5s

    # Преобразование данных из Docker API в метки (labels) Loki
    relabel_configs:
      # Служебные метки (с двойным _) в Loki не отправляются, задается конфигурация
      # их превращения в постоянные метки container и image.
      #
      # Например "__meta_docker_container_name": "/studyoverflow-1",
      # в результате "container": "studyoverflow-1"
      - source_labels: ['__meta_docker_container_name']
        # Все после слеша
        regex: '/(.*)'
        target_label: 'container'
        action: replace
      # Аналогично для image
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'

    # Список этапов (пайплайна), через которые проходит каждый лог перед отправкой в Loki
    pipeline_stages:
      # Этап json - парсит строку лога как JSON-объект и извлекает из него указанные поля,
      # задавая временные переменные для следующих этапов
      - json:
          expressions:
            level: levelname
            logger: name
            event_type: event_type

      # Этап использует переменные, заданные на этапе json и задает индексируемые
      # метки labels Loki.
      #
      # Метки ускоряют поиск сообщений, но выборка возможных значений должны быть небольшой,
      # user_id задавать не стоит.
      # Поиск за O(1) + O(m), где m - число отфильтрованных по label логов
      - labels:
          level:
          event_type:
          logger:
