# Конфигурация автоматического подключения (provisioning) источников данных к Grafana.
#
# Grafana при старте проверяет директорию /etc/grafana/provisioning/datasources/
# и регистрирует все описанные в ней источники данных (datasources) из всех .yml файлов.


# Задает версию формата, который указывает Grafana правила, по которым нужно считывать
# текущий конфиг. На данный момент Значение "1" - единственный стандарт для конфигурации.
apiVersion: 1

# Список подключаемых источников данных для Grafana
datasources:
  # Имя источника, отображаемое в веб-интерфейсе Grafana
  - name: Loki
    # Уникальный идентификатор источника внутри БД Grafana. Нужен, например, чтобы
    # связь между графиками дашборда и источником (loki) сохранилась при экспорте
    # дашборда из JSON при новой очищенной БД Grafana. В связи указывается именно
    # uid источника (а не имя), который меняется при обновлении БД Grafana.
    #
    # Дашборд - это визуальная панель с графиками, где каждый график имеет ссылку
    # на источник (через uid) с данными для его построения.
    uid: loki
    # Тип плагина источника данных. Указывает Grafana, какой драйвер и язык
    # запросов (LogQL для Loki) нужно использовать.
    type: loki
    # Режим адресации запросов от клиента к источнику (Loki).
    # proxy - клиент делает запрос к Grafana, а Grafana запрашивает данные у источника;
    # direct (browser в новых версиях) - клиент напрямую обращается к источнику, обычно
    # не используется, поскольку источник (Loki) обычно доступен только внутри Docker-сети.
    access: proxy
    # Сетевой адрес сервиса источника (Loki). Используется DNS Docker compose - вместо
    # loki подставится IP контейнера в локальной Docker-сети.
    url: http://loki:3100
    # Разрешает, если true, или не разрешает, если false, редактировать настройки источника
    # через веб-интерфейс.
    editable: true
    # Перезаписывает настройки источника в БД Grafana данными из конфига при каждом перезапуске
    # Docker-контейнера. При "editable: true" данные могут быть временно изменены, но они
    # сбросятся до настроек из конфига при рестарте Docker-контейнера.
    overwrite: true
    # Задает источник источником по умолчанию.
    isDefault: true
