# Конфигурация Loki. Loki - это специализированная NoSQL БД для хранения логов. Индексирует не текст сообщений,
# а метки labels. Поиск за O(1) + O(m), где m - число отфильтрованных по label логов. O(1) - поиск по labels,
# O(m) - поиск по логам в найденных чанках.
#
# В БД нет таблиц, она вся состоит из потоков. Каждый поток определяется уникальной комбинацией labels.
# Каждому потоку (комбинации меток) присваивается хеш. Все логи раскладываются по хешам.
#
# Логи для одного потока накапливаются в ОП в буфер, внутри буфера располагаются по времени.
# После истечение времени или заполнения буфера (лимит по памяти) данные в буфере сжимаются и
# сохраняются на диск, этот сжатый блок называется чанком (Chunk).
#
# Чанк сохраняется на жесткий диск как отдельный файл и относится к определенному потоку (хеш, набор labels).
# Все чанки лежат вместе в одном хранилище, но каждый относится к своему потоку.
# Сам чанк - это набор байт. Он не знает, к какому потоку относится. Для их связи используются индексы по labels.
# Внутри чанка labels нет.
#
# Индекс - отдельная структура данных, в которой хранится информация, какие чанки к какому потоку принадлежат.
# Индекс разделен по файлам по временным периодам. Поэтому берутся только подходящие файлы индекса для поиска чанков.
# Для каждого чанка в индексе записаны время его начала и конца MinTime и MaxTime (первый и последний логи).
# При поиске чанков через индексы проверяются, подходит ли хеш меток и пересекается ли время чанка [MinTime, MaxTime]
# с временем, указанным в запросе.
#
# Индекс выдает список ID чанков, в которых есть искомые логи за указанные временной период. После этого нужные чанки
# скачиваются, разархивируются, читаются и фильтруются.
#
# Затем логи читаются через Grafana. Grafana - это веб-интерфейс, клиент для чтения логов из Loki.


# Одиночный режим работы Loki, в один инстанс Loki пишет только один проект studyoverflow,
# не нужно настраивать, чтобы в один инстанс логи писали разные проекты, нет изоляции логов.
auth_enabled: false

# Настройки внутреннего сервера Loki для приема и отдачи данных
server:
  # Порт, на котором Loki принимает HTTP API запросы, от Promtail на запись и от Grafana на чтение
  http_listen_port: 3100

# Общие настройки Loki для разных его компонентов одного инстанса
common:
  # Рабочий каталог внутри Docker-контейнера для файлов
  path_prefix: /loki

  # Настройки хранилища логов
  storage:
    filesystem:
      # Путь к папке, где хранятся бинарные чанки с логами
      chunks_directory: /loki/chunks
      # Путь к папке для хранения правил оповещения и метрик
      rules_directory: /loki/rules

  # Коэффициент репликации данных, сейчас данные хранятся в 1 экземпляре
  replication_factor: 1

  # У Loki есть два режима работы: с одним экземпляром Loki и с несколькими, которые работают как одна БД,
  # даже при одиночном режиме ring требуется указывать.
  # ring - секция с настройкой распределенного кольца нод для координации нескольких экземпляров Loki
  ring:
    kvstore:
      # Loki работает в своей ОП, не пытается искать другие сервера Loki по сети
      store: inmemory

# Конфигурация индексации и хранения данных
schema_config:
  # Список конфигурация схемы, позволяет менять формат индекса по датам без потери старых логов
  configs:
      # Дата, насиная с которой Loki должен применять указанные настройки
    - from: 2026-01-01
      # Движок индекса
      store: tsdb
      # Место хранения чанков для данной схемы, задана локальная файловая система
      object_store: filesystem
      # Версия структуры схемы данных Loki, v13 - актуальна для TSDB
      schema: v13

      # Параметры разделения индекса на файлы и их именование
      index:
        # Префикс имени файлов индекса
        prefix: index_
        # Каждый файл индекса содержит данные за 24 часа, после создается новый файл
        period: 24h

# Лимиты хранения данных
limits_config:
  # Срок хранения логов в БД, логи старше указанного значения автоматически удаляются
  retention_period: 30d

# Настройки фонового процесса очистки старых логов
compactor:
  # Директория для обработки файлов при удалении
  working_directory: /loki/retention
  # Периодичность запуска проверки и удаления старых чанков,
  # а также слияния мелких индексных файлов в ходе работы (чтобы не держать
  # один большой файл в ОП все время, создаются маленькие файлы и записываются на диск)
  compaction_interval: 10m
  # Включает механизм очистки логов по истечению retention_period
  retention_enabled: true
  # Задержка перед физическим стиранием файлов с диска после пометки их устаревшими
  retention_delete_delay: 2h
  # Количество параллельных воркеров (потоков), занятых удалением старых файлов с диска
  retention_delete_worker_count: 10
