# Generated by Django 5.2.6 on 2025-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('posts', '0002_alter_post_slug'), ('posts', '0003_alter_post_content')]

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое поста'),
        ),
    ]
