# Generated by Django 5.2.6 on 2025-09-29 14:50

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('posts', '0004_lowercasetag_taggedpost_post_tags'), ('posts', '0005_alter_post_tags'), ('posts', '0006_alter_lowercasetag_name_alter_lowercasetag_slug')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0002_alter_post_slug_squashed_0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowercaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.lowercasetag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='posts.TaggedPost', to='posts.LowercaseTag', verbose_name='Теги'),
        ),
    ]
