# Generated by Django 5.2.6 on 2025-11-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowercasetag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
