# Generated by Django 5.2.6 on 2025-12-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_lowercasetag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create'], 'permissions': [('moderate_comment', 'Can moderate comments')], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'permissions': [('moderate_post', 'Can moderate posts')], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
