# Generated by Django 5.2.6 on 2026-01-11 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=15000, validators=[django.core.validators.MaxLengthValidator(15000)], verbose_name='Содержимое поста'),
        ),
    ]
