# Generated by Django 5.2.6 on 2026-01-15 11:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0013_alter_comment_content_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowercasetag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='taggedpost',
            options={'verbose_name': 'Тег поста', 'verbose_name_plural': 'Теги постов'},
        ),
        migrations.AlterField(
            model_name='lowercasetag',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='posts.lowercasetag'),
        ),
        migrations.AlterUniqueTogether(
            name='taggedpost',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
