# Generated by Django 5.2.6 on 2026-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_lowercasetag_options_alter_taggedpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rendered_content',
            field=models.TextField(blank=True, verbose_name='Отрендеренный текст (HTML из Markdown)'),
        ),
        migrations.AddField(
            model_name='post',
            name='rendered_content',
            field=models.TextField(blank=True, verbose_name='Отрендеренное содержимое (HTML из Markdown)'),
        ),
    ]
