# Generated by Django 5.2.6 on 2026-02-09 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0015_comment_rendered_content_post_rendered_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent_comment', '-time_create'], name='posts_comme_post_id_80be8b_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment', '-time_create'], name='posts_comme_parent__01cca1_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type_id', 'object_id'], name='posts_like_content_4ca6af_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-time_create'], name='posts_post_author__3c0cab_idx'),
        ),
        migrations.AddIndex(
            model_name='taggedpost',
            index=models.Index(fields=['object_id', 'content_type_id'], name='posts_tagge_object__c1dc59_idx'),
        ),
    ]
