# Generated by Django 5.2.6 on 2026-02-21 16:08

import posts.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment_posts_comme_post_id_80be8b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[posts.services.validators.PostTitleValidator(max_len=255, min_len=10)], verbose_name='Заголовок'),
        ),
    ]
