# Generated by Django 5.2.6 on 2026-06-19 19:12

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_title'),
    ]

    operations = [
        TrigramExtension(),
    ]
