# Generated by Django 5.2.6 on 2026-06-24 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("posts", "0020_comment_likes_count_post_comments_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taggedpost",
            name="posts_tagge_object__c1dc59_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["-likes_count", "-time_create"],
                name="posts_comme_likes_c_f6ac96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["likes_count", "-time_create"],
                name="posts_comme_likes_c_2486a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-likes_count", "-time_create"],
                name="posts_post_likes_c_f9ca0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["likes_count", "-time_create"],
                name="posts_post_likes_c_9a5ae9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-comments_count", "-time_create"],
                name="posts_post_comment_c8ea64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["comments_count", "-time_create"],
                name="posts_post_comment_8c098f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taggedpost",
            index=models.Index(
                fields=["object_id", "content_type"],
                name="posts_tagge_object__c1dc59_idx",
            ),
        ),
    ]
