# Generated by Django 5.2.6 on 2026-08-12 13:47

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_taggedpost_posts_tagge_object__c1dc59_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_content_trgm',
        ),
        migrations.AddField(
            model_name='post',
            name='search_content',
            field=models.TextField(blank=True, editable=False, verbose_name='Текст для поиска по содержимому'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rendered_content',
            field=models.TextField(blank=True, editable=False, verbose_name='Отрендеренное содержимое (HTML из Markdown)'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_content'], name='post_content_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
