# Generated by Django 5.2.6 on 2026-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_post_post_content_trgm_post_search_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowercasetag',
            name='posts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество постов'),
        ),
    ]
