# Generated by Django 5.2.6 on 2026-09-17 17:16

import posts.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_lowercasetag_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[posts.services.validators.PostTitleValidator(max_len=255, min_len=10, min_letters=10)], verbose_name='Заголовок'),
        ),
    ]
