# Generated by Django 5.2.6 on 2025-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_post', 'Лайк поста'), ('like_comment', 'Лайк комментария'), ('post_created', 'Пост создан'), ('comment_post', 'Комментарий к посту'), ('reply_comment', 'Ответ на комментарий'), ('user_register', 'Регистрация пользователя')], help_text='Тип уведомления', max_length=50, verbose_name='Тип'),
        ),
    ]
