# Generated by Django 5.2.6 on 2026-02-09 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_time_cr_a87b48_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-time_create'], name='notificatio_user_id_b1a2d7_idx'),
        ),
    ]
