# Generated by Django 5.2.6 on 2025-10-12 13:54

import users.services.domain
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0004_alter_user_username'), ('users', '0005_alter_user_username'), ('users', '0006_alter_user_username')]

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Имя пользователя должно быть не менее 4 символов и состоять только из латинских букв, цифр, символов '_' и '-'.", max_length=150, unique=True, validators=[users.services.infrastructure.CustomUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
