# Generated by Django 5.2.6 on 2025-10-12 14:07

import users.services.domain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username_squashed_0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[users.services.domain.PersonalNameValidator()], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[users.services.domain.PersonalNameValidator()], verbose_name='Фамилия'),
        ),
    ]
