# Generated by Django 5.2.6 on 2025-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_small',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Миниатюра аватара'),
        ),
    ]
