# Generated by Django 5.2.6 on 2025-10-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_small',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_small_size1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Миниатюра аватара №1'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_small_size2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Миниатюра аватара №2'),
        ),
    ]
