# Generated by Django 5.2.6 on 2025-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0010_remove_user_avatar_small_user_avatar_small_size1_and_more'), ('users', '0011_alter_user_avatar_small_size1_and_more')]

    dependencies = [
        ('users', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_small',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_small_size1',
            field=models.ImageField(blank=True, default='avatars/default_avatar_small_size1.jpg', upload_to='', verbose_name='Миниатюра аватара №1'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_small_size2',
            field=models.ImageField(blank=True, default='avatars/default_avatar_small_size2.jpg', upload_to='', verbose_name='Миниатюра аватара №2'),
        ),
    ]
