# Generated by Django 5.2.6 on 2025-10-23 11:35

import users.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_avatar_small_user_avatar_small_size1_and_more_squashed_0011_alter_user_avatar_small_size1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', upload_to='', validators=[users.services.AvatarFileValidator()], verbose_name='Аватар'),
        ),
    ]
