# Generated by Django 5.2.6 on 2025-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_update',
        ),
        migrations.AddField(
            model_name='user',
            name='answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_small_size3',
            field=models.ImageField(blank=True, default='avatars/default_avatar_small_size3.jpg', upload_to='', verbose_name='Миниатюра аватара №3'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='Был в сети'),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество постов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Репутация'),
        ),
    ]
