# Generated by Django 5.2.6 on 2025-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_time_update_user_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers_count',
        ),
        migrations.AddField(
            model_name='user',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
