# Generated by Django 5.2.6 on 2025-12-19 12:12

import users.services.infrastructure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='Через соцсеть'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', upload_to=users.services.infrastructure.user_avatar_upload_path, validators=[users.services.infrastructure.AvatarFileValidator()], verbose_name='Аватар'),
        ),
    ]
