# Generated by Django 5.2.6 on 2025-12-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_options_user_blocked_at_user_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('STAFF_VIEWER', 'Персонал (просмотр)'), ('USER', 'Пользователь')], default='USER', max_length=20, verbose_name='Роль'),
        ),
    ]
