# Generated by Django 5.2.6 on 2026-01-11 14:13

import django.core.validators
import users.services.infrastructure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[users.services.infrastructure.PersonalNameValidator()], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, validators=[users.services.infrastructure.PersonalNameValidator()], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Имя пользователя должно быть не менее 4 символов и состоять только из латинских букв, цифр, символов '_' и '-'.", max_length=30, unique=True, validators=[users.services.infrastructure.CustomUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
