# Generated by Django 5.2.6 on 2026-02-09 16:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0021_alter_user_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('username'), name='user_username_upper_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen'], name='users_user_last_se_f36183_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-reputation', 'username'], name='users_user_reputat_766558_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-posts_count', 'username'], name='users_user_posts_c_76c5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-comments_count', 'username'], name='users_user_comment_820365_idx'),
        ),
    ]
