# Generated by Django 5.2.6 on 2026-02-19 15:49

import users.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_user_username_upper_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, validators=[users.services.validators.BirthDateValidator()], verbose_name='Дата рождения'),
        ),
    ]
