# Generated by Django 5.2.6 on 2026-06-22 14:34

import django.core.validators
import users.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.services.validators.EmailUniqueValidator(), django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
