# Generated by Django 5.2.6 on 2026-08-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_email_user_unique_user_lowercase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s3_storage_uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUID "папки" аватарок в S3'),
        ),
    ]
