# Generated by Django 5.2.6 on 2026-08-31 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_populate_s3_storage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s3_storage_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID "папки" аватарок в S3'),
        ),
    ]
