# Generated by Django 5.2.6 on 2026-09-23 17:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0029_alter_user_s3_storage_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_lowercase_email',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_username_upper_idx',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('username'), name='unique_user_uppercase_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('email'), name='unique_user_uppercase_email'),
        ),
    ]
