[pytest]
# Имя файла с настройками проекта для тестирования
DJANGO_SETTINGS_MODULE = studyoverflow.settings.test

python_files = tests.py test_*.py *_tests.py

# Дефолтные аргументы запуска, не нужно прописывать при запуске тестов
# --nomigrations - создавать базу по моделям, не запуская миграции,
#     сейчас не используется с целью проверки корректности и актуальности миграций
# --reuse-db - не удалять тестовую БД после тестов (повторные тесты будут быстрее),
#     при появлении новых миграций нужно использовать флаг --create-db для обновления структуры тестовой БД
# --strict-markers - нельзя использовать незарегистрированные маркеры,
#     чтобы не пропускались опечатки в именах маркеров при запуске тестов
# -v - подробный формат результатов тестов
# -n 4 - запускать тесты параллельно в 4 процессах (через pytest-xdist)
addopts = --reuse-db --strict-markers -v -n 4

# Отключение экранирования не-ASCII символов
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

# Регистрация маркеров тестов
markers =
    # Использовать: @pytest.mark.slow,
    # запуски:
    #   pytest -m "not slow"
    #   pytest -m slow
    # В текущей версии проекта не используется
    slow: long-running tests

# Превращает Warnings в Exceptions, тесты упадут, если есть Warnings
filterwarnings =
    error
